repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
        exclude: ^tests/mock.py
      - id: no-commit-to-branch
        args: ["--branch", "main", "--branch", "dev"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - repo: local
    hooks:
      - id: type-check
        name: type check
        entry: make type-check
        language: system
        pass_filenames: false
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.12.0
    hooks:
      - id: commitizen-branch
        stages:
          - pre-push
  - repo: local
    hooks:
      - id: unit-test
        name: unit test
        entry: make unit-test
        language: system
        pass_filenames: false
