services:

  mongodb:
    image: mongo:7.0.15
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      retries: 5
      start_period: 10s
    networks:
      zexporta_custom_network:


    volumes:
      - /opt/mongo/db:/data/db

  redis:
    image: redis:latest
    restart: always
    volumes:
      - /opt/redis/data:/root/redis
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      retries: 5
      start_period: 10s
    networks:
      zexporta_custom_network:

  monitoring-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: zexporta
    container_name: monitoring-bot
    entrypoint: poetry run python -m zexporta.monitoring_bot.main
    networks:
      zexporta_custom_network:
        ipv4_address: 172.20.0.13
    volumes:
      - /var/log/zexporta/monitoring_bot/:/var/log/monitoring_bot/
    env_file:
      - .env.dev

  transfer-test-token-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: zexporta
    container_name: transfer-test-token-bot
    entrypoint: poetry run python -m zexporta.transfer_test_token_bot.main
    networks:
      zexporta_custom_network:
        ipv4_address: 172.20.0.14
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - /var/log/zexporta/transfer_test_token_bot/:/var/log/monitoring_bot/
    env_file:
      - .env.dev

  deposit-sa:
    build:
      context: .
      dockerfile: Dockerfile
    image: zexporta
    container_name: deposit-sa
    entrypoint: poetry run python -m zexporta.deposit.sa
    restart: always
    networks:
      zexporta_custom_network:
        ipv4_address: 172.20.0.4
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./zexporta/data:/app/zexporta/data
      - ./zexporta/dkgs/:/app/zexporta/dkgs/
      - /var/log/zexporta/deposit/:/var/log/deposit/
    env_file:
      - .env.dev

  deposit-observer:
    build:
      context: .
      dockerfile: Dockerfile
    image: zexporta
    container_name: deposit-observer
    entrypoint: poetry run python -m zexporta.deposit.observer
    restart: always
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./zexporta/data:/app/zexporta/data
      - ./zexporta/dkgs/:/app/zexporta/dkgs/
      - /var/log/zexporta/deposit/:/var/log/deposit/
    env_file:
      - .env.dev
    networks:
      zexporta_custom_network:
        ipv4_address: 172.20.0.6


  deposit-finalizer:
    build:
      context: .
      dockerfile: Dockerfile
    image: zexporta
    container_name: deposit-finalizer
    entrypoint: poetry run python -m zexporta.deposit.finalizer
    restart: on-failure:5
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./zexporta/data:/app/zexporta/data
      - ./zexporta/dkgs/:/app/zexporta/dkgs/
      - /var/log/zexporta/deposit/:/var/log/deposit/
    env_file:
      - .env.dev

    networks:
      zexporta_custom_network:
        ipv4_address: 172.20.0.7


  deposit-vault-depositor:
    build:
      context: .
      dockerfile: Dockerfile
    image: zexporta
    container_name: deposit-vault-depositor
    entrypoint: poetry run python -m zexporta.deposit.vault_depositor
    restart: always
    networks:
      zexporta_custom_network:
        ipv4_address: 172.20.0.8
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./zexporta/data:/app/zexporta/data
      - ./zexporta/dkgs/:/app/zexporta/dkgs/
      - /var/log/zexporta/deposit/:/var/log/deposit/
    env_file:
      - .env.dev

  withdraw-sa:
    build:
      context: .
      dockerfile: Dockerfile
    image: zexporta
    container_name: withdraw-sa
    entrypoint: poetry run python -m zexporta.withdraw.sa
    restart: always
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      zexporta_custom_network:
        ipv4_address: 172.20.0.5
    volumes:
      - ./zexporta/dkgs/:/app/zexporta/dkgs/
      - /var/log/zexporta/withdraw/:/var/log/withdraw/
    env_file:
      - .env.dev

  withdraw-observer:
    build:
      context: .
      dockerfile: Dockerfile
    image: zexporta
    container_name: withdraw-observer
    entrypoint: poetry run python -m zexporta.withdraw.observer
    restart: always
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      zexporta_custom_network:
        ipv4_address: 172.20.0.9
    volumes:
      - ./zexporta/dkgs/:/app/zexporta/dkgs/
      - /var/log/zexporta/withdraw/:/var/log/withdraw/
    env_file:
      - .env.dev

  validator-1:
    build:
      context: .
    image: zexporta
    container_name: validator-1
    entrypoint: poetry run gunicorn --bind 0.0.0.0:6002 --error-logfile - --capture-output --access-logfile - --capture-output --log-level debug  --workers=5 zexporta.validator.node:app
    environment:
      - NODE_ID=0xfd17e3847a110c89925baf6daed35c6f1ddf8bc9c8b38a9bb41096535b5f97fd
    restart: on-failure:5
    networks:
      zexporta_custom_network:
        ipv4_address: 172.20.0.10
    volumes:
      - ./zexporta/data:/app/zexporta/data
      - /var/log/zexporta/validator:/var/log/validator
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env.dev

  validator-2:
    build:
      context: .
    image: zexporta
    container_name: validator-2
    entrypoint: poetry run gunicorn --bind 0.0.0.0:6002 --error-logfile - --capture-output --log-level debug  --workers=5 zexporta.validator.node:app
    environment:
      - NODE_ID=0x0d67cd10c7b7b113b067d42c84a40dee850474892d5647955fdcb7a108b642ed
    restart: on-failure:5
    networks:
      zexporta_custom_network:
        ipv4_address: 172.20.0.11
    volumes:
      - ./zexporta/data:/app/zexporta/data
      - /var/log/zexporta/validator:/var/log/validator
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env.dev

  validator-3:
    build:
      context: .
    image: zexporta
    container_name: validator-3
    entrypoint: poetry run gunicorn --bind 0.0.0.0:6002 --error-logfile - --capture-output --log-level debug  --workers=5 zexporta.validator.node:app
    environment:
      - NODE_ID=0xfe6ec3f9e9ad332de8fcdf8d630ccdc209d54e71fcd9cc866785cebe2db5197b
    restart: on-failure:5
    networks:
      zexporta_custom_network:
        ipv4_address: 172.20.0.12
    volumes:
      - ./zexporta/data:/app/zexporta/data
      - /var/log/zexporta/validator:/var/log/validator
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env.dev

networks:
  zexporta_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
