[tool.poetry]
package-mode = false
name = "zexporta"
version = "0.0.1"
description = "Portal for Zellular Exchange"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
web3 = "~=6.19.0"
python-dotenv = "~=1.0.1"
pymongo = "~=4.10.1"
pydantic = "~=2.9.2"
httpx = "^0.27.2"
pyfrost = { git = "https://github.com/zellular-xyz/pyfrost.git" }
redis = "^5.2.0"
gunicorn = "^23.0.0"
fastapi = "^0.115.6"
sentry-sdk = "^2.19.2"

[tool.poetry.group.dev.dependencies]
pytest = "~=8.3.3"
pre-commit = "^4.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff.lint.per-file-ignores]
"config.py" = ["F401"]
