name: zex-fi/porta

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MONGO_HOST: localhost
      MONGO_PORT: 27017
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python and Install Dependencies
        uses: ./.github/actions/setup-python-uv

      - name: Run tests
        run: |
          make unit-test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python and Install Dependencies
        uses: ./.github/actions/setup-python-uv

      - name: Run linting
        run: |
          make lint

  build:
    needs:
      - test
      - lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build test
        run: |
          docker build .
